name: Publish Client.Base
on:
  push:
    tags:
      - 'Client.Base/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:23})
    - uses: actions/checkout@master
    - name: Add GPR source with credentials to NuGet.config
      shell: pwsh
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO_OWNER: Totopolis
        GH_SOURCE_NAME: GPR
      run: ./.github/workflows/AddSourceWithCredentialsToNuGetConfig -ConfigFile ./NuGet.Config -Source $env:GH_SOURCE_NAME -Username $env:GH_REPO_OWNER -Password $env:GH_TOKEN
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - run: dotnet pack ./src/Monik.Client.Base/Monik.Client.Base.csproj -c Release -o NuGetPackages /p:Version=$RELEASE_VERSION
    - name: Push to feeds
      env:
        MYGET_SOURCE: https://www.myget.org/F/totopolis/api/v3/index.json
        GH_SOURCE_NAME: GPR
      run: |
        dotnet nuget push ./NuGetPackages/Monik.Client.Base.$RELEASE_VERSION.nupkg -k ${{ secrets.MYGET_APIKEY }} -s $MYGET_SOURCE
        dotnet nuget push ./NuGetPackages/Monik.Client.Base.$RELEASE_VERSION.nupkg -s $GH_SOURCE_NAME